baseURL = "https://cukricek.github.io/267441_ZPC_2025/"
languageCode = 'cz-cs'
title = 'Moje portfolio predmetu ZPC'
theme = "ananke"

[[menu.main]]
  name = "O mne"
  url = "/posts/mne"
  weight = 10

[[menu.main]]
  name = "Príspevky"
  url = "/posts"
  weight = 20

[[menu.main]]
  name = "Domov"
  url = "/"
  weight = 30